# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ^ec_land_db/.*
repos:
  - repo: local # In order that we can reuse our defined local env, not one managed by pre-commit
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: ["python"]
        args:
          - "--check"

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: ["python"]
        args:
          - "--max-line-length=160"

      - id: isort
        name: isort
        entry: isort
        language: system
        types: ["python"]
        args: ["--profile", "black", --line-length=88] #to match the default line length in black so that isort and black don't conflict
